// <auto-generated/> — manual replacement for xunit.v3 auto-generated entry point.
// Uses ternary to satisfy CodeQL's "Missed ternary opportunity" rule.

return global::System.Linq.Enumerable.Any(args, arg => arg is "--server" or "--internal-msbuild-node")
    ? global::Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(
        args, RfcRag.Tests.SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult()
    : global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
