using System.Text.Json.Serialization;

namespace RfcRag.Answering;

/// <summary>
/// A structured answer generated by the LLM, with inline citations referencing evidence sections.
/// </summary>
public sealed record class GeneratedAnswer
{
    /// <summary>The answer text with inline citation markers (e.g., "[9110#9.3.1]").</summary>
    public required string Answer { get; init; }

    /// <summary>Citations extracted from the LLM response, each linking to evidence.</summary>
    public required IReadOnlyList<Citation> Citations { get; init; }

    /// <summary>The model identifier that produced this answer (null when unknown).</summary>
    public string? Model { get; init; }

    /// <summary>Why generation stopped (e.g., "stop", "length").</summary>
    public string? FinishReason { get; init; }

    /// <summary>When <see langword="true"/>, the question could not be answered from the available evidence.</summary>
    public bool NoAnswer { get; init; }
}

/// <summary>
/// A citation linking a claim in the answer to a specific evidence section.
/// </summary>
public sealed record class Citation
{
    /// <summary>Evidence id in "{RfcNumber}#{Section}" format, e.g. "9110#9.3.1".</summary>
    [JsonPropertyName("evidenceId")]
    public required string EvidenceId { get; init; }

    /// <summary>RFC number extracted from the evidence id.</summary>
    [JsonPropertyName("rfcNumber")]
    public int RfcNumber { get; init; }

    /// <summary>Section identifier extracted from the evidence id.</summary>
    [JsonPropertyName("section")]
    public required string Section { get; init; }

    /// <summary>Optional excerpt from the evidence that supports the claim.</summary>
    [JsonPropertyName("relevantText")]
    public string? RelevantText { get; init; }
}
