using System.Text.Json.Serialization;

namespace RfcRag.Answering;

/// <summary>
/// A structured answer generated by the LLM, with inline citations referencing evidence sections.
/// </summary>
public sealed record class GeneratedAnswer
{
    /// <summary>The answer text with inline citation markers (e.g., "[9110#9.3.1]").</summary>
    public required string Answer { get; init; }

    /// <summary>Citations extracted from the LLM response, each linking to evidence.</summary>
    public required IReadOnlyList<Citation> Citations { get; init; }

    /// <summary>The model identifier that produced this answer (null when unknown).</summary>
    public string? Model { get; init; }

    /// <summary>Why generation stopped (e.g., "stop", "length").</summary>
    public string? FinishReason { get; init; }

    /// <summary>When <see langword="true"/>, the question could not be answered from the available evidence.</summary>
    public bool NoAnswer { get; init; }

    /// <summary>Structured warnings produced while generating the answer.</summary>
    public IReadOnlyList<AnswerWarning> Warnings { get; init; } = [];

    /// <summary>Retrieval strategy and filters used to assemble the evidence.</summary>
    public RetrievalInfo? Retrieval { get; init; }
}


public sealed record class AnswerWarning
{
    public string Type { get; init; } = string.Empty;

    public string Message { get; init; } = string.Empty;

    public string? EvidenceId { get; init; }
}

/// <summary>Metadata describing how evidence retrieval was planned.</summary>
public sealed record class RetrievalInfo
{
    public string Strategy { get; init; } = string.Empty;

    public RetrievalFilters Filters { get; init; } = new();

    public RetrievalPlanInfo? Plan { get; init; }
}

/// <summary>Search filters applied during retrieval.</summary>
public sealed record class RetrievalFilters
{
    public string? NormativeKeyword { get; init; }


    public bool IncludeErrata { get; init; }

    public string? ErrataStatus { get; init; }
}

/// <summary>Deterministic query plan reported for traceability.</summary>
public sealed record class RetrievalPlanInfo
{
    public IReadOnlyList<int> RfcNumbers { get; init; } = [];

    public IReadOnlyList<RetrievalSectionReference> SectionReferences { get; init; } = [];

    public IReadOnlyList<int> ProtocolRfcNumbers { get; init; } = [];

    public string? SuggestedNormativeKeyword { get; init; }

    public bool HasAbnfIntent { get; init; }

    public bool IncludeObsolete { get; init; }

    public bool NeedsCurrentSpec { get; init; } = true;

    public IReadOnlyList<string> Rationale { get; init; } = [];
}

/// <summary>Explicit RFC section reference detected in a query.</summary>
public sealed record class RetrievalSectionReference
{
    public int RfcNumber { get; init; }

    public string Section { get; init; } = string.Empty;
}

/// <summary>
/// A citation linking a claim in the answer to a specific evidence section.
/// </summary>
public sealed record class Citation
{
    /// <summary>Evidence id in "{RfcNumber}#{Section}" format, e.g. "9110#9.3.1".</summary>
    [JsonPropertyName("evidenceId")]
    public required string EvidenceId { get; init; }

    /// <summary>RFC number extracted from the evidence id.</summary>
    [JsonPropertyName("rfcNumber")]
    public int RfcNumber { get; init; }

    /// <summary>Section identifier extracted from the evidence id.</summary>
    [JsonPropertyName("section")]
    public required string Section { get; init; }

    /// <summary>Optional excerpt from the evidence that supports the claim.</summary>
    [JsonPropertyName("relevantText")]
    public string? RelevantText { get; init; }
}
