namespace InfraGate.RfcRag.Models;

/// <summary>
/// A normative keyword occurrence found in an RFC section.
/// Normative keywords are defined in RFC 2119 / RFC 8174.
/// </summary>
public sealed record class NormativeOccurrence
{
    /// <summary>UUID primary key, generated by PostgreSQL.</summary>
    public Guid Id { get; init; }

    /// <summary>Foreign key to the parent RFC section.</summary>
    public Guid SectionId { get; init; }

    /// <summary>RFC number for denormalized lookup.</summary>
    public int RfcNumber { get; init; }

    /// <summary>The normative keyword: MUST, MUST NOT, REQUIRED, SHALL, SHALL NOT,
    /// SHOULD, SHOULD NOT, RECOMMENDED, MAY, OPTIONAL.</summary>
    public string Keyword { get; init; } = string.Empty;

    /// <summary>Line offset within the section text where the keyword appears.</summary>
    public int LineOffset { get; init; }
}
