namespace InfraGate.RfcRag.Models;

/// <summary>
/// An ABNF (Augmented Backus-Naur Form) grammar block extracted from an RFC section.
/// ABNF is the formal grammar notation used in IETF RFCs to define protocol syntax.
/// </summary>
public sealed record class RfcAbnfBlock
{
    /// <summary>UUID primary key, generated by PostgreSQL.</summary>
    public Guid Id { get; init; }

    /// <summary>Foreign key to the parent RFC section.</summary>
    public Guid SectionId { get; init; }

    /// <summary>RFC number for denormalized lookup.</summary>
    public int RfcNumber { get; init; }

    /// <summary>Section where this ABNF block appears.</summary>
    public string Section { get; init; } = string.Empty;

    /// <summary>The raw ABNF text block.</summary>
    public string AbnfText { get; init; } = string.Empty;

    /// <summary>Extracted rule names from the ABNF block (e.g., "request-line", "method").</summary>
    public string[] RuleNames { get; init; } = [];
}
