namespace InfraGate.RfcRag.Models;

/// <summary>
/// A section-level chunk of an RFC, stored as the primary searchable unit.
/// Each section is independently searchable via full-text, vector, and exact lookup.
/// </summary>
public sealed record class RfcSection
{
    /// <summary>UUID primary key, generated by PostgreSQL.</summary>
    public Guid Id { get; init; }

    /// <summary>RFC number (e.g., 9110).</summary>
    public int RfcNumber { get; init; }

    /// <summary>RFC title from the front matter (e.g., "HTTP Semantics").</summary>
    public string Title { get; init; } = string.Empty;

    /// <summary>Section number as a string (e.g., "6.3", "4.1.2", "Appendix A").</summary>
    public string Section { get; init; } = string.Empty;

    /// <summary>Section heading text (e.g., "Header Fields").</summary>
    public string? Heading { get; init; }

    /// <summary>The full text content of this section.</summary>
    public string Text { get; init; } = string.Empty;

    /// <summary>Relative path within the RFC mirror (e.g., "rfc9110.txt").</summary>
    public string SourcePath { get; init; } = string.Empty;

    /// <summary>Canonical URL to the RFC on rfc-editor.org.</summary>
    public string Url { get; init; } = string.Empty;

    /// <summary>SHA256 hash of the source file at indexing time, used for incremental re-index detection.</summary>
    public string SourceSha256 { get; init; } = string.Empty;

    /// <summary>Embedding vector dimensions match the configured embedding model.</summary>
    public float[] Embedding { get; init; } = [];
}
